#This file was automatically created by an EditorPlugin. Don't edit it, it will be overwritten.
extends Node
class_name Nodelist

const oGame = "/root/Game"
const oWorldChunks = "/root/Game/WorldChunks"
const oWorldGen = "/root/Game/WorldGen"
const oWorldInteract = "/root/Game/WorldInteract"
const oChunkUnloader = "/root/Game/ChunkUnloader"
const oTextureAtlas = "/root/Game/TextureAtlas"
const oCubeData = "/root/Game/CubeData"
const oOccluderManager = "/root/Game/OccluderManager"
const oCubeCollision = "/root/Game/CubeCollision"
const oPlayer = "/root/Game/Player"
const oCollisionBox = "/root/Game/Player/CollisionBox"
const oCamera = "/root/Game/Player/Camera"
const oPlayerLight = "/root/Game/Player/Camera/PlayerLight"
const oRayCaster = "/root/Game/Player/Camera/RayCaster"
const oTimerJumpCooldown = "/root/Game/Player/TimerJumpCooldown"
const oPlayerStartPosition = "/root/Game/PlayerStartPosition"
const oSelectorLight = "/root/Game/SelectorLight"
const oSunAngle = "/root/Game/SunAngle"
const oBlockSelector = "/root/Game/BlockSelector"
const oSelectorMesh = "/root/Game/BlockSelector/SelectorMesh"
const oBlockPlacer = "/root/Game/BlockPlacer"
const oCollisionShape = "/root/Game/BlockPlacer/CollisionShape"
const oShowPlacer = "/root/Game/BlockPlacer/ShowPlacer"
const oTimer = "/root/Game/BlockPlacer/Timer"
const oCrosshair = "/root/Game/Crosshair"
const oCrosshairSprite = "/root/Game/Crosshair/CrosshairSprite"
const oExtraInfo = "/root/Game/ExtraInfo"
